# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Elior.Rafalsky-TestSub(0d645574-51fe-47fd-8fcb-cd1bfbd0444d)'
    appType: 'webAppLinux'
    appName: 'my-app-dotnet123444432'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'